apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava
  labels:
    app: strava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava
  template:
    metadata:
      labels:
        app: strava
    spec:
      containers:
      - name: strava
        image: registry.home.timvw.be/strava:0.1
        ports:
        - containerPort: 9000
        imagePullPolicy: "Always"
        env:
        - name: STRAVA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: strava
              key: STRAVA_CLIENT_ID
        - name: STRAVA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: strava
              key: STRAVA_CLIENT_SECRET
        - name: PUBLIC_HOST
          value: https://strava.home.timvw.be
---
apiVersion: v1
kind: Service
metadata:
  name: strava
  labels:
    app: strava  
spec:
  selector:
    app: strava
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strava
  labels:
    app: strava  
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - strava.home.timvw.be
    secretName: strava-home-tls-secret
  rules:
  - host: strava.home.timvw.be
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: strava
            port:
              number: 9000
